### ISSUE TITLE
How to change the default listening port

### ISSUE THREAD

**Issue by eoekun** [gskinner/regexr#281]
Hi,when I use the command `gulp`, the port `3000` is inuse,how can I  run it without kill the process which using port `3000`?
```bash
[eoekun@eoekun regexr]$ gulp
[10:27:24] Using gulpfile ~/home/eoekun/regexr/gulpfile.js
[10:27:24] Starting 'browser-sync'...
[10:27:24] Finished 'browser-sync' after 12 ms
[10:27:24] Starting 'build-js'...
[10:27:24] Starting 'build-sass'...
[10:27:25] Starting 'watch'...
[10:27:25] Finished 'watch' after 58 ms
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at Server.setupListenHandle [as _listen2] (net.js:1355:14)
    at listenInCluster (net.js:1396:12)
    at Server.listen (net.js:1480:7)
    at module.exports.plugin (/home/eoekun/regexr/node_modules/_browser-sync@2.24.7@browser-sync/dist/server/index.js:27:25)
    at Object.startServer [as fn] (/home/eoekun/regexr/node_modules/_browser-sync@2.24.7@browser-sync/dist/async.js:177:52)
    at /home/eoekun/regexr/node_modules/_browser-sync@2.24.7@browser-sync/dist/browser-sync.js:120:14
    at iterate (/home/eoekun/regexr/node_modules/_browser-sync@2.24.7@browser-sync/dist/utils.js:253:13)
    at /home/eoekun/regexr/node_modules/_browser-sync@2.24.7@browser-sync/dist/utils.js:264:25
```

**Comment by Heziode** [comment]
Hi @eoekun,

This issue is related to [Browsersync options - port](https://www.browsersync.io/docs/options#option-port).

To change the port you need to edit [gulpfile.js line 37](https://github.com/gskinner/regexr/blob/master/gulpfile.js#L37) like this:
```js
// current version
// browserSync.init({ server: { baseDir: "./" }, options: { ignored: "./dev/**/*"} });

// version with you port
browserSync.init({ server: { baseDir: "./" }, options: { ignored: "./dev/**/*"}, port: 4000 });
```

This will make browserSync listen on port 4000 instead of 3000

You can also do something smarter by using environment variable

**Comment by gskinner** [comment]
That's correct. Thanks @Heziode
